config/routes.rb
Rails.application.routes.draw do

  resources :landing
  
  get    'feed'           => 'feed#account', as: 'feed'
  get    'feed/:tag'      => 'feed#show', as: 'feed_show'
  get    'recent'         => 'feed#recent', as: 'recent'
  post   'feed/add'       => 'feed#add', as: 'feed_add'
  get    'trending'       => 'feed#trending', as: 'trending'
  get    'gravity/:tag'   => 'feed#gravity', as: 'gravity'
  get    'search'         => 'feed#search', as: 'search'
  
  get    'account'                  => 'account#panel', as: 'account_panel'
  get    'account/not_verified/:id' => 'account#not_verified', as: 'account_not_verified'
  get    'account/verify/:code'     => 'account#verify', as: 'account_verify'
  post   'account/resend-code'      => 'account#resend_code', as: 'account_resend_code'
  
  patch   'account_settings'       => 'account_settings#update', as: 'account_settings_update'
  
  get    'member/new'       => 'member#new', as: 'member_new'
  post   'member/new'       => 'member#create', as: 'member_create'
  get    'member/success'   => 'member#success'
  
  get    'session/login'            => 'session#login', as: 'session_login'
  post   'session/login'            => 'session#authenticate'
  post   'session/logout'           => 'session#logout', as: 'session_logout'
  
  get    'question'             => 'question#index'
  post   'question'             => 'question#ask', as: 'question_ask'
  get    'question/:id'         => 'question#show', as: 'question_show'
  delete 'question/:id/delete'  => 'question#delete', as: 'question_delete'
  
  post   'question/:id/answer'   => 'answer#new', as: 'answer_new'
  delete 'answer/:id/delete'     => 'answer#delete', as: 'answer_delete'
  
  post   'answer/:id/vote'   => 'vote#cast', as: 'vote_cast'

  get    'group/new'          => 'group#new', as: 'group_new'
  post   'group/create'       => 'group#create', as: 'group_create'
  get    'group/:id'          => 'group#show', as: 'group_show'
  get    '/i/:code'           => 'group#invite', as: 'group_invite'
  delete 'group/:id/leave'    => 'group#leave', as: 'group_leave'
  
  get   'privacy'   => 'static_pages#privacy', as: 'privacy'
  
  root   'landing#index'
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  # Validations
  validates :tag, uniqueness: true, allow_nil: true
  validate :one_primary_per_account
  
  # Relationships
  belongs_to :account
  has_many :question_banks, dependent: :destroy
  
  # Validation
  # Each account can only have one primary feed
  def one_primary_per_account
    if Feed.where(account: account, primary: true).count > 1
      errors.add(:tag, "can't have more than one primary feed")
    end
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  # How many items show per page
  WillPaginate.per_page = 18
  
  def show
    @question = Question.new
    
    # Search first by tag, then ID
    @feed = Feed.find_by tag: params[:tag]
    if !@feed
      @feed = Feed.find(params[:tag])
    end
    
    @questions = @feed.question_banks.collect{ |bank| bank.question }
    set_page_data Feed.filter_by_page(params[:page], @questions)
    authorize! :read, @feed
    render layout: "full-width"
  end
  
  # What's hot
  def trending
    @question = Question.new
    
    # Get a list of questions sorted by rating
    @questions = Question.only_public.order("rating desc").where.not(rating: nil).paginate({
      :page => params[:page]
    })
    
    render layout: "full-width"
  end
  
  # Get all recent questions
  def recent
    @question = Question.new
    @questions = Question.only_public.order("created_at desc").paginate({
      :page => params[:page]
    })

    render layout: "full-width"
  end
  
  # Search for stuff
  def search
    
  end
  
  # Get questions by tag
  def gravity
    @question = Question.new
    tag = params[:tag]
    if Tag.exists?(name: tag)
      @questions = Tag.find_by(name: tag).questions.order("created_at desc").paginate({
        page: params[:page]
      })
      render layout: "full-width"
    else
      @questions = []
      flash[:notice] = "Bummer, '#{params[:tag]}' tag exist. Why don't you tag something with it?"
    end
  end
  
  def account
    if current_account.primary_feed
      redirect_to feed_show_path(current_account.primary_feed) and return
    end
    
    @feed = Feed.new
  end
  
  def add
    question_id = params[:question_id]
    @question = Question.find(question_id)
    
    feed_id = params[:feed_id]
    
    # If no feed was supplied, check if the account has a feed.
    # If they do, add it to that, otherwise create a new one
    if !feed_id
      # Does the user have a primary feed?
      if current_account.primary_feed
        @feed = current_account.primary_feed
      else
        @feed = Feed.create({
          account: current_account,
          name: "My Feed",
          private: true,
          primary: true
        })
      end
    else
      @feed = Feed.find(feed_id)
    end
    authorize! :add, @feed
    @question_bank = QuestionBank.new(feed: @feed, question: @question)
    
    if @question_bank.save
      redirect_to feed_show_path(@feed.id)
    else
      flash[:error] = "You already have that question in your feed"
      redirect_to :feed
    end
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/feed/_nav.html.erb
<nav class="feed-nav">
  <% live = live || "" %>
  <%= link_to "Trending", :trending, class: (live == "trending" ? "live" : "") %>
  <%= link_to "Recent", :recent, class: (live == "recent" ? "live" : "") %>
</nav>

app/views/feed/_question.html.erb
<article class="question">
  <h1 class="placeholder"><%= link_to @question.entry, question_show_path(@question) %></h1>
  <section class="tags">
    <ul>
      <% @question.tags.take(3).each do |tag| %>
        <li><%= link_to tag.name, gravity_path(tag.name) %></li>
      <% end %>
    </ul>
  </section>
  <ul class="answers">
  <% @answers = @question.answers.sort_by{ |answer| answer.votes.count }.reverse.take(5) %>
    <% if  @answers.count < 1 %>
      <span class="lite">No answers yet.</span>
    <% end %>
    <% @answers.each do |answer| %>
      <li>
        <a href="<%= vote_cast_path(answer.id) %>" data-method="post">
          <div class="counter <%= "answered" if current_account.voted_on?(answer) %>"><%= answer.votes.count %></div>
          <% entry = answer.entry %>
          <div class="answer-entry"><%= entry %></div>
        </a>
      </li>
    <% end %>
    <li class="suggest-answer">
      <%= link_to "View Question", question_show_path(@question) %> &middot;
      <%= link_to "Suggest an Answer...", question_show_path(@question) %>
    </li>
  </ul>
</article>

app/views/feed/_questions.html.erb
<section class="questions-container">
  <%= "<p>There's no questions here yet.</p>".html_safe if @questions.count < 1 %>
  <% @questions.each do |question| %>
    <% @question = question %>
    <%= render 'feed/question' %>
  <% end %>
</section>
<% if @questions %>
  <section class="pages">
    <%= will_paginate @questions %>
  </section>
<% end %>

app/views/feed/account.html.erb
<div class="feed">
  <h1>My Feed</h1>
  <p>You don't have any questions in your feed.</p>
</div>

app/views/feed/gravity.html.erb
<%= render 'nav', :live => 'gravity' %>
<%= render 'question/form' %>
<section class="feed-content">
  <%= render 'questions' %>
</section>

app/views/feed/recent.html.erb
<%= render 'nav', :live => 'recent' %>
<%= render 'question/form' %>
<section class="feed-content">
  <%= render 'questions' %>
</section>

app/views/feed/search.html.erb
<h1>Search isn't ready yet</h1>

app/views/feed/show.html.erb
<%= render 'nav', :live => "show" %>
<%= render 'question/form' %>
<section class="feed-content">
  <%= render 'questions' %>
</section>

app/views/feed/trending.html.erb
<%= render 'nav', :live => 'trending' %>
<%= render 'question/form' %>
<section class="feed-content">
  <%= render 'questions'%>
</section>