config/routes.rb
Rails.application.routes.draw do

  resources :landing
  
  get    'feed'           => 'feed#account', as: 'feed'
  get    'feed/:tag'      => 'feed#show', as: 'feed_show'
  get    'recent'         => 'feed#recent', as: 'recent'
  post   'feed/add'       => 'feed#add', as: 'feed_add'
  get    'trending'       => 'feed#trending', as: 'trending'
  get    'gravity/:tag'   => 'feed#gravity', as: 'gravity'
  get    'search'         => 'feed#search', as: 'search'
  
  get    'account'                  => 'account#panel', as: 'account_panel'
  get    'account/not_verified/:id' => 'account#not_verified', as: 'account_not_verified'
  get    'account/verify/:code'     => 'account#verify', as: 'account_verify'
  post   'account/resend-code'      => 'account#resend_code', as: 'account_resend_code'
  
  patch   'account_settings'       => 'account_settings#update', as: 'account_settings_update'
  
  get    'member/new'       => 'member#new', as: 'member_new'
  post   'member/new'       => 'member#create', as: 'member_create'
  get    'member/success'   => 'member#success'
  
  get    'session/login'            => 'session#login', as: 'session_login'
  post   'session/login'            => 'session#authenticate'
  post   'session/logout'           => 'session#logout', as: 'session_logout'
  
  get    'question'             => 'question#index'
  post   'question'             => 'question#ask', as: 'question_ask'
  get    'question/:id'         => 'question#show', as: 'question_show'
  delete 'question/:id/delete'  => 'question#delete', as: 'question_delete'
  
  post   'question/:id/answer'   => 'answer#new', as: 'answer_new'
  delete 'answer/:id/delete'     => 'answer#delete', as: 'answer_delete'
  
  post   'answer/:id/vote'   => 'vote#cast', as: 'vote_cast'

  get    'group/new'          => 'group#new', as: 'group_new'
  post   'group/create'       => 'group#create', as: 'group_create'
  get    'group/:id'          => 'group#show', as: 'group_show'
  get    '/i/:code'           => 'group#invite', as: 'group_invite'
  delete 'group/:id/leave'    => 'group#leave', as: 'group_leave'
  
  get   'privacy'   => 'static_pages#privacy', as: 'privacy'
  
  root   'landing#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  # Validations
  validates :entry, presence: true, length: { maximum: 125 }
  validates :account, presence: true
    
  # Relationships
  belongs_to :account
  belongs_to :feed
  belongs_to :group
  
  has_many :answers, dependent: :destroy
  has_many :question_banks, dependent: :destroy
  has_and_belongs_to_many :tags
  
  # Rates a current question based on votes and answers
  def rate
    votes = answers.inject(0) do |sum, a| 
      sum + a.votes.count 
    end
    
    # Return a count of votes and answers
    answers.count + votes
  end
  
  # Is the question public?
  def public?
    # If it's not in a group, it's public
    if group
      !group.private
    else
      true
    end
  end
  
  scope :only_public, -> { where(group: nil) }
  
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_filter :require_verified_account
  
  def index
    @question = Question.new
  end
  
  def ask
    # Create a new question
    new_params = question_params
    new_params[:tags] = Tag.process_all(new_params[:tags])
    if new_params[:group]
      new_params[:group] = Group.find(new_params[:group])
    end
    @question = Question.new(new_params)
    @question.account = current_account
    
    authorize! :create, @question
    
    # Save the question
    if @question.save
      
      # Check if there's a group for this question
      if @question.group
        
        # Go through each member and send emails to each
        # with correct account settings
        @question.group.accounts.each do |account|
          # Don't send to the current account
          if account != current_account
            
            # Create a mail item
            mailer = TransactionMailer.group_post(@question, account)
            
            # Only send it if it's valid
            if mailer
              mailer.deliver
            end
          end
        end
      end
      
      # Redirect to the question
      redirect_to question_show_path(@question)
    else
      flash[:errors] = @question.errors.full_messages.join(", ")
      redirect_to :back
    end
  end
  
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @vote = Vote.new
    
    if @question.group
      unless current_account.group_member? @question.group
        flash[:error] = "You need to login to see this question"
        session[:routes] = { "login" => question_show_path(@question) }
        redirect_to :session_login and return
      end
    end
    
    # Get all the answers and sort them
    @answers = @question.answers.sort_by do |answer| 
      answer.votes.count
    end.reverse
    
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "We couldn't find that question"
      redirect_to trending_path
  end
  
  def delete
    @question = Question.find(params[:id])
    authorize! :destroy, @question
    if @question.destroy
      flash[:notice] = "Good bye, dear question."
    else
      flash[:error] = "Well shoot, we couldn't delete that question."
    end
    redirect_to :trending
  end
  private
  def question_params
    params.require(:question).permit(:entry, :tags, :group)
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/question/_form.html.erb
<section class="feed-question-new">
  <%= form_for @question, :url => question_ask_path do |f| %>
    <% if @question.errors.any? %>
      <div>
        <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <% if defined? question_group %>
        <% placeholder = "Ask #{ question_group.name } something..." %>
      <% else %>
        <% placeholder = "Ask anyone..." %>
      <% end %>
      <%= f.text_area :entry, class: "feed-question-field", title: placeholder, placeholder: placeholder %>
    </div>
    <footer>
      <% if defined? question_group %>
        <%= f.hidden_field :group, value: question_group.id %>
      <% end %>
      <%= f.hidden_field :tags %>
      <div class="tag-bin"></div>
      <%= '<p>You must login to submit an answer.</p>'.html_safe if current_account.guest? %>
      <%= f.submit "Ask Question", class: "feed-question-submit" %>
      <div class="character-counter"></div>
    </footer>
  <% end %>
</section>

app/views/question/index.html.erb
<%= render 'question/form' %>

app/views/question/show.html.erb
<%= render 'feed/nav' %>
<main class="show-question">
  <h1><%= @question.entry %></h1>
  <% if @question.group %>
    <p>In <%= link_to @question.group.name, group_show_path(@question.group) %></p>
  <% end %>
  <h2 class="time">Asked <%= time_ago_in_words(@question.created_at) %> ago by <%= @question.account.display_name %></h2>
  <div class="actions">
    <ul>
      <li>
        <%= link_to "Delete Question", 
      question_delete_path(@question), class:"delete-question", :method => "delete", :data => { confirm: "You sure?" } if can? :destroy, @question %>
      </li>
      <li>
        <%= form_tag feed_add_path, id: "add-to-feed" do %>
          <%= hidden_field_tag :question_id, @question.id %>
        <% end %>
        <!-- <a href="#" onclick="$('#add-to-feed').submit()" class="button">Add to Feed</a> -->
      </li>
    </ul>
  </div>
  <section class="tags">
    <ul>
      <% @question.tags.each do |tag| %>
        <li><%= link_to tag.name, gravity_path(tag.name) %></li>
      <% end %>
    </ul>
  </section>
  <section class="bin">
    <ul class="answers">
      <% if  @answers.count < 1 %>
        <span class="lite">No answers yet.</span>
      <% end %>
      <% @answers.each do |answer| %>
        <li>
          <a href="<%= vote_cast_path(answer.id) %>" data-method="post">
            <div class="counter <%= "answered" if current_account.voted_on?(answer) %>"><%= answer.votes.count %></div>
            <% entry = answer.entry %>
            <div class="answer-entry"><%= entry %></div>
          </a>
          <%= link_to image_tag("delete-white.svg"), answer_delete_path(answer), class: "delete-answer", method: :delete, data: { confirm: "You sure?" } if can? :destroy, answer %>
        </li>
      <% end %>
    </ul>
  </section>
  <footer>
    <% @answer = @answer || Answer.new %>
    <%= form_for @answer, :url => answer_new_path(@question), :method => "post" do |f| %>
      <% if @answer.errors.any? %>
        <div>
          <ul>
            <% @answer.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :entry, value: '', placeholder: "Suggest an Answer..." %>
      <%= '<p>You must login to submit an answer.</p>'.html_safe if current_account.guest? %>
      <%= f.submit "Submit Answer" %>
    <% end %>
  </footer>
</main>