config/routes.rb
Rails.application.routes.draw do

  resources :landing
  
  get    'feed'           => 'feed#account', as: 'feed'
  get    'feed/:tag'      => 'feed#show', as: 'feed_show'
  get    'recent'         => 'feed#recent', as: 'recent'
  post   'feed/add'       => 'feed#add', as: 'feed_add'
  get    'trending'       => 'feed#trending', as: 'trending'
  get    'gravity/:tag'   => 'feed#gravity', as: 'gravity'
  get    'search'         => 'feed#search', as: 'search'
  
  get    'account'                  => 'account#panel', as: 'account_panel'
  get    'account/not_verified/:id' => 'account#not_verified', as: 'account_not_verified'
  get    'account/verify/:code'     => 'account#verify', as: 'account_verify'
  post   'account/resend-code'      => 'account#resend_code', as: 'account_resend_code'
  
  patch   'account_settings'       => 'account_settings#update', as: 'account_settings_update'
  
  get    'member/new'       => 'member#new', as: 'member_new'
  post   'member/new'       => 'member#create', as: 'member_create'
  get    'member/success'   => 'member#success'
  
  get    'session/login'            => 'session#login', as: 'session_login'
  post   'session/login'            => 'session#authenticate'
  post   'session/logout'           => 'session#logout', as: 'session_logout'
  
  get    'question'             => 'question#index'
  post   'question'             => 'question#ask', as: 'question_ask'
  get    'question/:id'         => 'question#show', as: 'question_show'
  delete 'question/:id/delete'  => 'question#delete', as: 'question_delete'
  
  post   'question/:id/answer'   => 'answer#new', as: 'answer_new'
  delete 'answer/:id/delete'     => 'answer#delete', as: 'answer_delete'
  
  post   'answer/:id/vote'   => 'vote#cast', as: 'vote_cast'

  get    'group/new'          => 'group#new', as: 'group_new'
  post   'group/create'       => 'group#create', as: 'group_create'
  get    'group/:id'          => 'group#show', as: 'group_show'
  get    '/i/:code'           => 'group#invite', as: 'group_invite'
  delete 'group/:id/leave'    => 'group#leave', as: 'group_leave'
  
  get   'privacy'   => 'static_pages#privacy', as: 'privacy'
  
  root   'landing#index'
end

app/views/layout/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57001861-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layout/_flash.html.erb
<% if flash.any? %>
  <ul class="page-notices">
    <% flash.each do |notice| %>
      <li class="<%= notice[0] %>"><%= notice[1] %></li>
    <% end %>
  </ul>
<% end %>

app/views/layout/_footer.html.erb
<footer class="page-footer">
  <div><a href="mailto:hello@asknow.io">We love feedback</a></div>
  <p class="fine-print">
    &copy; 2014 Mealey Dev, LLC. All rights reserved. <%= link_to "Terms and Privacy", :privacy %>
 </p>
</footer>

app/views/layout/_head.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1" />
<head>
  <title><%= @page_title || "Ask Now · Get real-time answers from real people" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layout/_header.html.erb
<header class="header">
  <a class="logo" href="<%= trending_path %>">
    <img src="/assets/logo.svg"/>
  </a>
  <p class="account-snippet">
    <%= link_to current_account.display_name, account_panel_path %>
  </p>
</header>

app/views/layout/_nav.html.erb
<button class="open-menu"><img src="/assets/open-menu.svg" alt="Menu"></button>
<nav class="menu">
  <button class="close-menu"><img src="/assets/close-menu.svg" alt="Close"></button>
  <ul>
    
    <li><%= link_to "Trending", :trending %></li>
    <li><%= link_to "Recent", :recent %></li>
    <p>Account</p>
    <li><%= link_to "Ask a Question", :question %></li>
    <% if current_account.guest? %>
    <li><%= link_to "New Account", :member_new %></li>
    <li><%= link_to "Login", :session_login %></li>
    <% else %>
    <li><%= link_to "Panel", :account_panel %></li>
    <li><%= link_to "Logout", :session_logout, method: "post"  %></li>
    <% end %>
    <p>Groups</p>
    <% if current_account.groups %>
      <% current_account.groups.limit(6).each do |group| %>
        <li><%= link_to group.name, group_show_path(group) %></li>
      <% end %>
    <% end %>
  </ul>
</nav>