config/routes.rb
Rails.application.routes.draw do

  resources :landing
  
  get    'feed'           => 'feed#account', as: 'feed'
  get    'feed/:tag'      => 'feed#show', as: 'feed_show'
  get    'recent'         => 'feed#recent', as: 'recent'
  post   'feed/add'       => 'feed#add', as: 'feed_add'
  get    'trending'       => 'feed#trending', as: 'trending'
  get    'gravity/:tag'   => 'feed#gravity', as: 'gravity'
  get    'search'         => 'feed#search', as: 'search'
  
  get    'account'                  => 'account#panel', as: 'account_panel'
  get    'account/not_verified/:id' => 'account#not_verified', as: 'account_not_verified'
  get    'account/verify/:code'     => 'account#verify', as: 'account_verify'
  post   'account/resend-code'      => 'account#resend_code', as: 'account_resend_code'
  
  patch   'account_settings'       => 'account_settings#update', as: 'account_settings_update'
  
  get    'member/new'       => 'member#new', as: 'member_new'
  post   'member/new'       => 'member#create', as: 'member_create'
  get    'member/success'   => 'member#success'
  
  get    'session/login'            => 'session#login', as: 'session_login'
  post   'session/login'            => 'session#authenticate'
  post   'session/logout'           => 'session#logout', as: 'session_logout'
  
  get    'question'             => 'question#index'
  post   'question'             => 'question#ask', as: 'question_ask'
  get    'question/:id'         => 'question#show', as: 'question_show'
  delete 'question/:id/delete'  => 'question#delete', as: 'question_delete'
  
  post   'question/:id/answer'   => 'answer#new', as: 'answer_new'
  delete 'answer/:id/delete'     => 'answer#delete', as: 'answer_delete'
  
  post   'answer/:id/vote'   => 'vote#cast', as: 'vote_cast'

  get    'group/new'          => 'group#new', as: 'group_new'
  post   'group/create'       => 'group#create', as: 'group_create'
  get    'group/:id'          => 'group#show', as: 'group_show'
  get    '/i/:code'           => 'group#invite', as: 'group_invite'
  delete 'group/:id/leave'    => 'group#leave', as: 'group_leave'
  
  get   'privacy'   => 'static_pages#privacy', as: 'privacy'
  
  root   'landing#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  # Validations
  validates :name, presence: true
  
  # Relationships
  has_many :questions
  has_many :group_members
  has_many :accounts, through: :group_members
  
  before_save :generate_invite_code
  
  def default_member_permission
    GroupMemberPermission.find(default_permission)
  end
  
  # Creates a random invite code, this isn't the most secure
  # way to do this, but it's a lot easier to share.
  def generate_invite_code
    loop do
      self.invite_code = (0...8).map { (65 + rand(26)).chr }.join
      break unless Group.find_by(invite_code: invite_code)
    end
  end
  
  # Get that user's permissions
  def account_permission(account)
    group_members.joins(:account).where(account: account).first.group_member_permission
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def new
    @group = Group.new
  end
  
  def create
    # Add group info
    @group = Group.new(group_params)
    
    authorize! :create, @group
    # Save the group
    if @group.save
      # Add the user a member
      group_member = GroupMember.new({
        group: @group,
        account: current_account,
        owner: true,
        group_member_permission: GroupMemberPermission.powerizer
      })
      
      if group_member.save
        flash[:notice] = "Sweet! You started the #{@group.name} group, now invite people."
        redirect_to group_show_path(@group.id)
      else
        flash[:error] = "Bummer, we had a problem saving the group"
        logger.error(group_member.inspect)
        render 'new'
      end
    else
      render 'new'
    end
  end
  
  def show
    @group = Group.find(params[:id])
    
    unless current_account.group_member? @group
      flash[:error] = "You can't view that group"
      redirect_to :trending and return
    end
    
    @question = Question.new
    @questions = @group.questions
    @questions = @questions.order("created_at desc").paginate({
      page: params[:page]
    })
    
    render layout: "full-width"
  end
  
  # You just got invited to a group
  def invite
    invite_code = params[:code]
    
    # Grab the group
    @group = Group.find_by(invite_code: invite_code)
    
    # Check if that group exists
    if @group
      # If they're a guest, prompt them to sign up or login
      if current_account.guest?
        session[:routes] = { "login" => group_invite_path(invite_code) }
        flash[:notice] = "To join #{ @group.name }, login or sign up."
        redirect_to :session_login
      
      # Are they already part of that group?
      elsif current_account.group_member?(@group)
        # Redirect to the group
        redirect_to group_show_path(@group) and return
      else
        authorize! :join, @group

        # Create a new group member
        group_member = GroupMember.new({
          account: current_account,
          group: @group,
          group_member_permission: @group.default_member_permission
        })

        # Try saving the member
        if group_member.save
          flash[:notice] = "Welcome to #{@group.name}, #{current_account.display_name}"
          redirect_to group_show_path(@group)
        else
          flash[:error] = group_member.errors.full_messages.join(",")
          redirect_to :trending
        end
      end
    else
      flash[:error] = "That invite code is bad, bummer dude."
      redirect_to :trending
    end
  end
  
  def leave
    @group = Group.find(params[:id])
    
    if current_account.group_member? @group
      if @group.group_members.find_by(account: current_account).destroy
        flash[:notice] = "You left #{@group.name}."
        redirect_to :account_panel
      else
        flash[:error] = "Something went wrong and we couldn't delete you from that group."
        redirect_to :back
      end
    else
      flash[:error] = "Couldn't find that group."
      redirect_to :back
    end
  end
  
  private
  def group_params
    params.require(:group).permit(:name, :private, :default_permission)
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/invite.html.erb
<div class="group-invite">
  <h1>Join <%= @group.name %></h1>
</div>

app/views/group/new.html.erb
<h1>Start a New Group</h1>
<main class="new-group">
  <%= form_for @group, :url => group_create_path do |f| %>
    <% if @group.errors.any? %>
      <div>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <section class="bin">
      <div>
        <h3>Pick a name that describes your group.</h3>
        <%= f.text_field :name, placeholder: "Group name..." %>
      </div>
      <ul class="group-options">
        <li>
          Default members
          <select name="group[default_permission]">
            <% GroupMemberPermission.all.each do |p| %>
              <option value="<%= p.id %>"><%= p.powers %></option>
            <% end %>
          </select>
        </li>
      </ul>
    </section>
    <div>
      <%= f.submit "Create Group" %>
    </div>
  <% end %>
</main>

app/views/group/show.html.erb
<%= render 'feed/nav', :live => @group.id %>
<div class="show-group">
  <div class="group-question-form">
    <%= render 'question/form', :question_group => @group %>
  </div>
  <main class="group-questions">  
    <section class="feed-content">
      <%= render 'feed/questions'%>
    </section>
  </main>
  <aside class="group-details">
    <h1><%= @group.name %></h1>
    <div><%= link_to "Leave Group", group_leave_path(@group), :class => "leave-group", :method => "delete", :data => { confirm: "You sure you don't want to be a part of this group?" }%></div>
    <% if @group.account_permission(current_account).invite %>
      <p>Invite anyone to <%= @group.name %></p>
      <input type="text" class="auto-highlight" value="<%= group_invite_url(@group.invite_code) %>">
    <% end %>
    <h2>Group Members</h2>
    <ul class="group-members">
      <% @group.accounts.each do |account| %>
        <li><%= account.display_name %></li>
      <% end %>
    </ul>
  </aside>
</div>